### ISSUE TITLE
dependency resolution issue kache-common

### ISSUE THREAD

**Issue by koolfreak** [MayakaApps/Kache#100]
![image](https://user-images.githubusercontent.com/1182352/235293214-fd252493-b92a-4e48-8da2-eb72a5294b73.png)

com.cybernetics.cyrclo:test: Could not find Kache:kache-common:unspecified.
Required by:
    project : > com.mayakapps.kache:kache-jvm:2.0.0-SNAPSHOT:20230429.030344-34

**Comment by MSDarwish2000** [comment]
Thank you for reporting this. I'll be fixing it as soon as possible.

**Comment by MSDarwish2000** [comment]
Closing this as fixed. If it still doesn't work for you, please build using this command to refresh snapshot dependencies.

`./gradlew build --refresh-dependencies`
