### ISSUE TITLE
API inconsistency in `directory` vs `directoryPath`

### ISSUE THREAD

**Issue by sschuberth** [MayakaApps/Kache#107]
While migrating from DiskLru, it occurred to me that there's an API inconsistency in the directory parameters: The `FileKache` class / invoke function takes `directoryPath` as a `String`, whereas everywhere else it's `directory` as a `Path`. Is it worth to align that on `Path` for the 2.0.0 final release?

**Comment by MSDarwish2000** [comment]
If you are talking about the argument name, I think it is true that it is better to share the naming convention. 

But the main purpose of `FileKache` and `JavaFileKache` is to match the used file handling method in the application. If I'm an Android or JVM developer who don't need Okio for my current application, then it would be better to pass `File` directory to `JavaFileKache` and expect put and get functions to use `File` as well. While, if I'm Kotlin/Native developer who prefer to use `fopen` and so on, I'd prefer to pass the directory as a `String` and expect the same from the put and get functions as well.

Feel free to explain your opinion more and thank you for collaborating.

**Comment by sschuberth** [comment]
> If you are talking about the argument name, I think it is true that it is better to share the naming convention.

Actually, I'm more referring to the type... which somewhat implies the naming, as it basically makes sense to me that the two directory-style parameters of different types (`String` vs. `Path`) are also named differently to highlight the difference.

> While, if I'm Kotlin/Native developer who prefer to use `fopen` and so on, I'd prefer to pass the directory as a `String`

I admit I haven't thought about Kotlin/Native. Seems like you're put some though on this and the inconsistency (from JVM perspective) isn't an oversight, so I'm closing this. Thanks for the reply!
