### ISSUE TITLE
Configuration vs function parameters

### ISSUE THREAD

**Issue by sschuberth** [MayakaApps/Kache#109]
The FileKache `invoke()` functions take the directory and maxSize in addition to Configuration as parameters. However, directory and maxSize can also be passed via Configuration itself. While this probably was done this way for user convenience (to configure most common parameters more easily), I believe this makes things more confusing, as the semantics are unclear if e.g. the directory is provided both as a direct argument and via Configuration (precedence is unclear then). To guard against unintended misuse, I'd recommend to drop the direct function parameters and rely solely on the Configuration.

**Comment by MSDarwish2000** [comment]
You are right that precedence needs to be clarified in the documentation of the function. But it was designed like that to make sure that the user knows and provides required arguments at compile-time. This is suggested in the [guidelines of Kotlin Libraries](https://kotlinlang.org/docs/jvm-api-guidelines-readability.html#use-builder-dsl) as well.

For now, if the value is provided through both methods, the configuration block takes precedence.

**Comment by sschuberth** [comment]
> But it was designed like that to make sure that the user knows and provides required arguments at compile-time.

I see. I was pretty sure Kotlin would offer a more elegant way (from the DSL perspective) for this, but [apparently it doesn't](https://stackoverflow.com/a/58173654/1127485).

Shall we still keep this open as a reminder the precedence should be documented?

**Comment by MSDarwish2000** [comment]
@sschuberth Sure. It is OK to keep it open. 

Also, another option for this is to remove the required arguments from `Configuration` and keep them as function parameters only. It would reduce the confusion for precedence but make the configuration split even more, I think.

**Comment by sschuberth** [comment]
> It would reduce the confusion for precedence but make the configuration split even more, I think.

Indeed, and splitting configuration shouldn't be an option, IMO.
