### ISSUE TITLE
Duplicate class androidx.* found

### ISSUE THREAD

**Issue by vfsfitvnm** [MayakaApps/Kache#170]
**Describe the bug**
This library defines several `androidx` classes that make the task `:checkDebugDuplicateClasses` fail with the following error:
```
Duplicate class androidx.annotation.IntRange found in modules annotation-jvm-1.7.0 (androidx.annotation:annotation-jvm:1.7.0) and kache-jvm (com.mayakapps.kache:kache-jvm:2.1.0-beta01)
Duplicate class androidx.collection.MapEntry found in modules collection-jvm-1.4.0-rc01 (androidx.collection:collection-jvm:1.4.0-rc01) and kache-jvm (com.mayakapps.kache:kache-jvm:2.1.0-beta01)
[...]
```
I see some minor edits have been applied to the original classes; I guess this shouldn't (and cannot) be resolved with Gradle.
Is it on purpose?

**Comment by MSDarwish2000** [comment]
Thank you for reporting the issue.

The reason for copying the original classes is defined in each copied source file. In summary, this is done to adapt `MutableScatterMap` to be used for the cache. The issue was fixed and a new release would be out shortly with the fix.
