### ISSUE TITLE
Stable version of Kache

### ISSUE THREAD

**Issue by joshuawilliams-qz** [MayakaApps/Kache#192]
I am wondering if we would be able to receive a stable version of Kache. Right now, I believe the only [available](https://mvnrepository.com/artifact/com.mayakapps.kache/kache) versions of Kache are beta versions. When do you think we would be able to see version 2.1.0?

**Comment by MSDarwish2000** [comment]
Thank you for your interest and sorry for late response. You're correct that all Multiplatform Kache versions are beta versions. Yet, the latest beta version is well-tested and used in production, so I'm planning to release it out as v2.1.0 after dependency and docs updates. I'm hoping to do this within a day.

**Comment by MSDarwish2000** [comment]
Closing this as the stable version is currently available.
