### ISSUE TITLE
Please add some tests 😉 

### ISSUE THREAD

**Issue by sschuberth** [MayakaApps/Kache#5]
I just came across this library, and while it looks interesting, I'm hesitating to take it into use in [ORT](https://github.com/oss-review-toolkit/ort) to replace [DiskLruCache](https://github.com/JakeWharton/DiskLruCache), mostly because of a complete lack of tests.

So, would it be possible to add tests to get some confidence into the implementation?

**Comment by MSDarwish2000** [comment]
Thank you for your suggestion. I'll try to add test coverage to it as soon as possible.

**Comment by MSDarwish2000** [comment]
@sschuberth Sorry for being late. I've started in the process of going multiplatform and adding tests. I've done `LruCache` part. I understand that you're interested in `DiskLruCache` more but I think your feedback on the current progress will help me. Feel free to review new code and tests and let me know if you have any suggestions or issues.

**Comment by sschuberth** [comment]
Now I'm sorry for being late, @MSDarwish2000 😉 While I still didn't have time to review all existing tests, one thing came to my mind: The [original DiskLruCache](https://github.com/JakeWharton/DiskLruCache) implementation had several shortcomings, like a [maximum key length of 64 chars](https://github.com/oss-review-toolkit/ort/blob/eb34b0dd11ee08ddbb537aa3c7eb54ecb7ff5bd7/utils/common/src/main/kotlin/DiskCache.kt#L56-L59) and several [natural chars being invalid for cache keys](https://github.com/oss-review-toolkit/ort/blob/eb34b0dd11ee08ddbb537aa3c7eb54ecb7ff5bd7/utils/common/src/main/kotlin/DiskCache.kt#L71-L74). Would it make sense to add tests that these limitations don't exist in your implementation?

**Comment by MSDarwish2000** [comment]
@sschuberth Thank you for your suggestion.  That seems to be a good example of integration test for both DiskLruCache and the default KeyTransformer. Surely, I'll add it once I have time to resume developing the library.

**Comment by MSDarwish2000** [comment]
I'm closing this as completed for now. I'm currently focusing on finalizing the new release as for anyone waiting for it as I don't have enough time for now. More tests pull requests for persistent (or in-memory) caches are welcome. I'm closing this as the situation has changed a lot since this was opened.
